var _ = require('underscore');

module.exports = function (scriptLoader) {
    var quotes = [
            'Es ist kaum zu fassen, aber ich fühle mich vom Fernsehen irgendwie verarscht.',
            'Im Gegensatz zu den meisten von euch bin ich kein armer Irrer.',
            'Nur Spanner gaffen noch, wenn meine alten rumknutschen.',
            'Wer hätte gedacht, dass es so einen Spass machen könnte, einen Jungen ins Mädchenklo zu schubsen. Das Gekreische, die Demütigung, die Tatsache, dass es nicht mir passiert ist.' ,
            'Spiegelglatze hör auf zu jammern.',
            '1000 Dollar weniger, dass macht für den Chef einen Elfenbeinrückenkratzer weniger.',
            'Aber es steht in Tarifvertrag jährlich eine pro forma Beförderung aus der Belegschaft.',
            'Oh eine politische Diskussion bei Tische. ICh komm mir vor wie eine echte Kennedy.',
            'Dieser Burns ist genau das was unser Staat braucht, junges Blut. ',
            'Nur Dummköpfe trinken Bier.',
            'Ich kanns nicht glauben, du hast tatsächlich die praktische Seite der Geometrie entdeckt.',
            'Barmherzigkeit ist für die Schwachen Todd!',
            'Hallo Vermittlung welche Nummer hat die 110?',
            'Von der Wiege bis zur Bahre feste Gewohnheiten sind das einzig wahre.',
            'Schulhofgerüchte entsprechen gewöhnlich den Tatsachen, gehen aber am essenziellen vorbei.',
            'Es ist unser Hund, wir können seine Integrität und seinen Charakter in Frage stellen, aber Wir dürfen nicht an seinem Herzen zweifeln. Willst du uns etwa beibringen, dass man ein Problem mit jemanden den man liebt am besten dadurch löst, indem man ihn verstößt.',
            'Wer Bart wählt, wählt Anarchie!',
            'Ich hab die Arbeit satt. Abrbeit ist was für Ideoten.',
            'Mein Sohn ich bin stolz auf dich, ich war doppelt so alt, als ich das herausgefunden habe.',
            'Diese Witzbolde. Wenn der Kern explodiert, kiergt doch das Warnsystem keinen Strom mehr.',
            'Du kennst seine Blutgruppe. Och wie romantisch.',
            'Gratuliere Junge, du kriegst ein Rendevouz mit einer Nadel.',
            'Es ist nicht unsere Schuld, wir wollten den Jungen ja gar nicht, es war ein Betriebsunfall.',
            'Als dann der Arzt sagte, dass ich keine Würmer mehr hätte, war das der glücklichste Tag in meinem Leben.',
            'Geld kommt und Geld geht, aber die Liebe meiner Tochter kann noch acht Jahre dauern!',
            'Wir machen heute einen Test. Er nennt sich Qualifikationsaufgabentest für Schulabgänger, kurz: Quatsch.',
            'Trotz eines Harvard-Diploms endet man vielleicht als Babysitter für eine Horde stumpfsinniger Viertklässler, während der Ehemann nackt am Strand rumläuft mit deiner Eheberaterin.',
            'Machst du mir die Milch auf, Mama?',
            'Du hast genug Köpfchen um weit nach oben zu kommen. Und wenn du soweit bist, dann bin ich sofort wieder da, um mir Kohle von dir zu pumpen.',
            'Ich werde nie wieder die Unwissenheit des Lehrkörpers bloßstellen.',
            'Der Lümmel trinkt das Wasser!',
            'Mein Name ist Otto, sauf dich blöd ist mein Motto.',
            'Ok Gehirn. Wenn du dich jetzt anstrengst, füll ich dich nachher wieder voll mit Alkohol!',
            'Ich bin so klug!  K.L.U.K.!',
            'Lassen sie die Rolling Stones umbringen!',
            'Wir könnten uns viele nützliche Dinge kaufen, wie Liebe.',
            'Ich stimme dir theoretisch zu. Theoretisch funktioniert auch der Kommunismus.',
            'Bonjour, ihr käsefressenden Kapitulationsaffen!',
            'Ich bin nicht gestört! Du bist gestört! Und das ganze bescheuerte System ist gestört! Soll ich dir die Wahrheit sagen? Willst du's genau wissen? Abe du erträgst sie nicht, die Wahrheit! Erst wenn du die Hand ausstreckst und sie in einem widerlichen Brei stecken bleibt, der mal das Gesicht dein besten Freundes war, dann weißt du was du tun musst! Vergiss es, Marge! Das ist Chinatown!',
            'Darauf bin ich gekommen, als ich gemerkt habe, dass es im Kühlschrank kalt ist.',
            'Ich verbringe den Sommer damit, einen alten Freund, genannt Fernsehen, etwas besser kennen zu lernen.',
            'Feiern wir unsere neu Abmachung mit dem Hinzufügen von Schokolade in die Milch.',
            'Ich sagen, ich finds gar nicht mal so übel, ich verbringen den Sommer damit einen alte Freund, genannt Fernsehen etwas besser kennen zu lernen.',
            'Halt die Klappe Hirn! Ich hab jetzt Freunde, ich brauch dich jetzt nicht mehr.',
            'Der Atem meiner Katze riecht nach Katzenfutter!',
            'Euer schuldiges Gewissen treibt euch dazu, die Demokraten zu wählen. Aber tief in eurem Innern sehnt ihr euch nach einem kaltherzigen Republikaner,  der die Steuern senkt, Verbrecher brutalisiert und euch regiert wie ein König.',
            'Findest du es nicht auch merkwürdig, dass Uter plötzlich verschwunden ist und uns jetzt dieser geheimnisvolle Uter-Braten vorgesetzt wird?',
            'Liegt's an meiner Frisur? An meinem Überbiss? Oder daran, dass ich seit vier Jahren tagtäglich die selben Sachen trage?',
            'Du machst aus mir noch einen richtigen Verbrecher, dabei will ich doch nur ein kleiner Gauner werden.',
            'Vergiss bitte nicht, ich bin das liebe Pfarrerstöchterchen und du bist nur gelber Müll!',
            'Ich war der Typ, der Star Trek abgesetzt hat!',
            'Lieber will ich in eiskalter Erde begraben sein als das ich Missouri anerkenne!',
            'Waren du solltest endlich aufhören das Okular anzubeten.',
            'Dutzende Menschen werden Tag für täglich in Springfield niedergeschossen. Doch bis jetzt war keins der Opfer von Bedeutung.',
            'Kinder, Kinder, Kinder, was euren Daddy betrifft, hält der euch beide für potentielle Mörder.',
            'Man kann nie wissen, wozu man im Leben fähig ist. Ich hätte nie gedacht, dass ich ein deutsches Flugzeug abschießen könnte, aber im letzten Jahr hab ich mir das Gegenteil bewiesen.',
            'Jetz pass mal auf Opi kein Gericht der Welt würde ein Baby verurteilen, hm höchstens in Texas.',
            'Wenn ich groß bin geh ich auch auf die Büffeluniversität.',
            'Wann werden die Leute das es endlich begreifen. Demokratie funktioniert einfach nicht.',
            'Was ist eigentlich los hier in diesem Land? Kann man nicht mal die Straße entlang laufen, ohne ein Stellenangebot zu bekommen?',
            'Habt ihr gesehen, wie die Leute sich nicht gegenseitig schubsen und O.K. schlagen? An einem so einem Ort bin ich noch nie im Leben gewesen.',
            'Hm, nur einen Dollar für ewiges Glück? Naja... hm... trotzdem bin ich glücklicher mit dem Dollar.',
            'Ich bin hier in diesem Altenheim geboren und ich werde hier in diesem Altenheim sterben!',
            'Neddie glaubt nicht an Versicherungen, er betrachtet das als so eine Art Spiel.',
            'Ich habe sogar koscher gelebt, um auf Nummer sicher zu gehen.',
            'Ich habe alles getan, was in der Bibel steht, selbst den Mist, der an anderer Stelle widerrufen wird!',
            'Das kann doch nur die kleine Lisa Simpson sein, Springfields Antwort auf eine Frage, die nie gestellt wurde!',
            'Der letzte Fall, dem Sie auf den Grund gegangen sind, war die Tüte mit Schokoriegeln!',
            'Eigentlich fröstelt's mich ein bisschen, könnte ich noch eine Zwangsjacke haben?',
            'Ja sie müssen uns helfen Doktor. Wir haben nichts versucht und wir haben auch nicht die geringste Ahnung.',
            'Und wenn mich jemand auf die Palme bring, überfahre ich ihn mit meinem Wagen.',
            'Teamwork ist überbewertet',
            'Ich bin der Auffassung, Mogeln ist eine Begabung, die der Mensch sich selbst verleiht.',
            'Du kennst mich Marge, ich mag mein Bier kalt, meinen Fernseher laut und meine Homosexuellen sollen sich outen!',
            'Auf den Alkohol! Der Ursprung und die Lösung sämtlicher Lebensprobleme!',
            'Willie hört euch und Willie ist das egal.',
            'Schalt bitte um auf nen anderen Kanal Marge.',
            'Kann niemand Recht und Ordnung selbst in die Hand nehmen.',
            'Grafiti von nem Denkmal abwaschen, verspottet alles wofür ich eintrete. Das werd ich hier sicher nicht überleben Lisa.',
            'Das weiß ich auch nicht, aber bestimmt was scharf gewürztes.',
            'Du kannst jetzt nicht abhauen, bei mir zu Hause wird eine alte Frau reingelegt!',
            'Du hast Hitlers Auto kaputt gemacht. Was hat er dir nur getan?',
            'Her damit du nudelarmiger Chorknabe',
            'Oh, das Internet gibt's jetzt auch schon für Computer!',
            'Ja, er ist meine absolute Lieblings-Science-Fiction-Figur!',
            'Wenn deine Nase anfängt zu bluten, hast du wahrscheinlich zu viel darin gebohrt! Oder zu wenig.',
            'Nicht vergessen Otto, wir vertrauen Ihnen hiermit unseren wertvollsten Schatz an: den Schulbus.',
            'Ich glaub' ich mach' mich selbst zum Vizepräsident. Nein warte, Juniorvizepräsident!',
            'Schuldigung, ich wusste nicht, dass du und Jay Leno und ein Affe einen Clown badet.',
            'Hallo, ich bin Moe, in der Frauenwelt aber besser bekannt als Hey, du da, hinter den Büschen!.',
            'Nukular. Es heißt Nukular',
            'Mein Homer ist kein Kommunist! Er ist vielleicht ein Lügner, ein Schwein, ein Idiot, ein Kommunist, aber er ist ganz sicher kein Pornostar!',
            'Wir haben alle von Anfang an gewusst, dass dieser Blödsinn nicht funktioniert.',
            'Jetzt nehmen wir nen Schlückchen und dann schlafen wir nen Stückchen.',
            'Du willst ihn zerquetschen, stimmt's?',
            'Das soll doch woll ein Witz sein, oder? Das ist der dümmste Artikel den ich je gelesen hab'. Sie benutzen wunderliche Worte wie Pasghetti und Marmaten. Der Bericht enthält auch zahlreiche Drohungen gegen die Uno und gegen Ende wiederholen sie dauernd die Worte: Zum Teufel mit Flanders!. Immer und immer wieder',
            'Komm schon, wütender Dad, werd' wütend, sonst muss ich was aus alten Folgen zusammenstoppeln!',
            'Wenn sich Bart El Barto nennen darf, dann darf ich mich El Homo nennen',
            'Marge wach auf. Die Zeitung spricht zu mir.',
            'Hey villeicht hat der ausgebrochene Geisteskranke, den sie engagiert haben in seinem Schuppen ne Priese Gift. Ja Hallo Willie.',
            'Meine Nase kann Bubblegum produzieren!',
            'Nein ich bin nicht in der Verfasssung zu fahren. Warte ich sollte nicht auf mich selbst hören, ich bin zu betrunken.',
            'Lass mich ans Steuer. Ich fahr auch über gelbe Ampeln.',
            'Jede Woche ein neuer Blumenstrauß. Ich wünschte ich wäre tot.',
            'Aber wir haben doch schon ein Buch.',
            'Euch zuzuhören ist mehr Folter als Folter.',
            'Ja ganz toll, die können wir uns auch später ansehn.',
            'Muss was essen, dann aufs Klo, dann wieder was essen, dann auf den Klo was essen.',
            'Junge lass dich mal näher anknabbern.',
            'Homer! Du willst meine gefüllten Paprika nicht essen, aber du isst unseren Sohn?',
            'Sag meinen Freunden ich bin gestorben, als ich ein Mädchen geküsst hab.',
            'Muss noch mehr fette Menschen essen. Zum Glück bin ich in Amerika.',
            'Ich muss ehrlich zu dir sein. Ich kann unmöglich einen Menschenfresser lieben, der 4000 Tonnen wiegt.',
            'Ich glaub ich brauch ne halbe Tonne Koks, um diese miese Nummer aufzuziehen.',
            'Bart, ich muss dir jetzt etwas von Vater zu Sohn sagen. Ich bin auf deiner Schildkröte eingeschlafen und hab sie erstickt. Gern geschehen.',
            'Hey Bart ich hab mir den Kopf rasiert, wie du gesagt hast.',
            'Als Dünger werden sie nützlicher sein als als Mensch.',
            'Ich bin vielleicht halbiert, aber ich habe noch Gefühle',
            'Die Lösung für alle Probleme eines Mannes ist eine gut funktionierende Beziehung',
            'Ja besorg ihm eine Frau das wird sein Leiden beenden.',
            'Er hat die Haut nicht gefressen, dass ist gesund.',
            'Wir mussten sie angreifen, die haben heimlich Massenverblödungswaffen hergestellt.',
            'Ich habe 3 Kinder und kein Geld. Wieso kann ich nicht keine Kinder haben und 3 Geld?',
            'Ich will so ein Vergessensdrink. Ich muss einen Auftritt von mir auslöschen. Ich wollte als Goerge Bush Witze über Araber machen, aber ich habe als Mel Gibson Witze über Mexikaner gemacht.',
            'Du möchtes das ich mich für dich an was erinnere? Dann kannst du auch dein Pferd fragen, ob es deine Steuer macht, was ich 1989 getan hab',
            'Ach ich vermisse die alten Zeiten am Anfang dieser Woche.',
            'Ich brauche jemand wie Bart, nur mit was in der Birne ... Lisa!',
            'Wah ein zweites ich! Du passt auf die Kinder auf.',
            'Ich habs ihrer Frau schon besorgt, das wird ihr morgen ganz schön weh tun',
            'Naja, wer in Neuronenaktiovator sitzt sollte nicht mit Erinnerungen werfen.',
            'In meinem Schweinie ist zu wenig Geldie.',
            'Das ist Bildungsfernsehn, nur durch die eingespielten Lacher, lernt unser Volk was Humor ist.',
            'Ach wenn ich Marge sehe erinnert mich das immer an Marge.',
            'Die Ratte symbolisiert filmische Redundanz.',
            'Tja eine Ratte frisst die andere, genau wie ich beim Abendessen gestern.',
            'Er ist immer gut drauf, aber um zu wissen worauf, braucht man seine Urinprobe.',
            'Sohn, das Müntzsammeln ist fast genauso wie das Leben. Es hat schon vor langer Zeit aufgehört Spaß zu machen.',
            'Lieber Sterben als Hassen.',
            'Wenn sie mir ihr Badezimmer zeigen, würde ich gerne so tun, als ob ich mir die Hände wasche.',
            'Die Sonnenfinsternis ist dann, wenn ich es sage!',
            'Weißt du meine Kleine, ich ging zu den Freimauern bevor es in war. Das ist mein Auge auf der Eindollarnote und meine Pyramide.',
            'Superman, ich habe Jahre an dich geglaubt, wenn du mich hören kannst, bitte komm und Hilf mir diese Grab auszuheben.',
            'Tut mir Leid, aber ich weiß ganz sicher, dass Gott niemals von einer Mutter verlangen würde, dass sie ihr Kind für das Wohl der Welt opfert. Nicht nochmal.,
            'Ich hab ihn eine anderes Juwelenkind da gelassen.',
            'Ha ich werd meine Bettgehzeit sowas von überziehen.',
            'Vierblättrige Kleeblätter sind keine mutierten Freaks.',
            'Du hast mir auch etwas gesagt, aber ich hab nicht zugehört.',
            'Komm schon tauf deine Arschbacken.',
            'Dunkilderry ist so malerisch, es sieht aus, wie das Puzzle im Wartezimmer vom Kinderarzt.',
            'Du hast das Prinzip des Familienausflugs noch nicht verstanden. Wir unternehmen etwas zusammen, während sich euer Vater ohne uns amüsiert.',
            'Wir brauchen Hilfe, jemanden der mit einer Bar, die keine Gäste und keine Atmosphäre hat, Geld verdienen kann.',
            'Es ist viel besser geworden, seit wir unser inkompetenten Idioten nach Amerika schicken, wo ihr sie aus irgendwelchen Gründen zu Polizisten macht.',
            'Sie hat das selbe wunderschöne Gesicht, wie mein Großonkel Magnus, als er im Sarg lag nach seinem Unfall mit dem Leiterwagen.',
            'Mit deinem Tran würden unsere Lampen ein Jahr brennen.',
            'Maggies erste Worte sind auf Ogdenvillianisch!',
            'Jetzt weiß ich, warum Hummer immer diesen fröhlichen Schrei loslassen wenn sie in den Topf fallen!',
            'Mach einfach die Augen zu und denk an Milhouse.',
            'Der Junge soll so lange arbeiten, bis er gelb wird!',
            'Ich würde alles Leben auf diesem Planeten vernichten, nur um nie wieder bruchrechnen zu müssen.',
            'Express heiß, dass ihr jeden Gast so schnell wie möglich beleidigen sollt.',
            'Immer wenn du Unrecht hast, brabbelst du Schwachsinn.',
            'Und wieder hat Schlaf in der Arbeit meine Ehe gerettet.',
            'Wenn sich keiner ärgern lies, warst du dann wirklich richtig mies?',
            'Das ist normalerweise der Zeitpunkt an dem ich aufwache. Jetzt komm schon Wecker hol mich raus!',
            'Ich habe falsch abgeschrieben. Ich hab den Namen von Lisa genommen und dazu die Antworten von Ralph.',
            'Geh zu Grandpa, der war auch mal ein Mann.',
            'Gib deine Schätze frei du gelber Teufel.',
            'Heute Vormittag hat ihr Sohn unangemessenen Mund-zu-Mundkontakt mit unserer Tochter aufgenommen.',
            'Machen sie ihre Schule zu einer zuneigungsfreien Zone oder wir klagen die letzten zehn Cent aus ihnen raus.',
            'Das ist hammermäßig, wenn das echte Leben doch auch in 3-D wäre.',
            'Gut Dung will Weile haben.',
            'Hey Willie schmeckt er auch wie ein Versager?',
            'Nein Nikki. Lieber ein totes Schulkind, als ein Prozess mit deinen Eltern.',
            'Ich bin Jugendlicher und wenn ich nicht in jedem zweiten Satz einen Computerausdruck höre, mach ich nen Abgang.',
            'Homer ich höre deinen Sarkasmus bis in de Küche rüber und das obwohl die Spülmaschine läuft.',
            'Mehr Platz in der Hölle für mich.',
            'Dieses Land hat soviel Geschichte. Wer weiß, vielleicht hat Jesus sogar eine Predigt in Konferenzraum C gehalten?',
            'Israel ist das sicherste Land auf der Erde. Die einzige Gefahr hier ist Dehydratation.',
            'Schalom ist das Alohwa von der Gegend hier.',
            'Ich les Gebete und ignorier sie, wie Gott.',
            'Du kämpfst nicht wie ein Mädchen, nicht mal wie ein Milhouse.',
            'Amerikanische Penner wie dich fertig machen zählt als mein Militärdienst.',
            'Ah-ha ein Sandpferd, das Auto der Wüste',
            'Viel Glück wenn du ohne mich überleben willst!',
            'Ist das salzig. Vielleicht sollte ich noch etwas nach salzen.',
            'Fällt dir auf, dass Dad immer die Krankheit kriegt, die im Boardmagazin beschrieben wird?',
            'Verbreitet das Wort: Friede und Hähnchen',
            'Ironie des Schicksals nach all meinen Jahren voll Börsenbetrug, Waffenhandel, versuchen Morden, gelungenen Morden und Spannerei, Sitze ich wegen eines   kleinen Multimilliardendollar Kunstraubs.',
            'Ich bin auch schon wiederauferstanden, das wird überschätzt.',
            'Soll sie den Rest ihres Lebens in Freiheit verbringen oder lassen wir sie in Gefangenschaft sterben wie Grandpa?',
            'Hey wenn Wünsche Pferde wären, würde ich jeden Abend Wunschfleisch essen.',
            'Der Krieg ist vorbei und die Zukunft hat gewonnen, die Vergangenheit hatte nie eine Chance man.',
            'Krustofski sortieren sie die Penner nachdem Krieg in dem sie waren!',
            'Also ich muss mir meine Unterwäsche in diesem Dorf in der Ukraine spezial anfertigen lassen. Die nennen mich Daddy RundRund.',
            'Wohau jetzt weiß ich endlich wie sich eine hochschwangere Frau fühlt.',
            'Betrunken und ordnungswidrig, dass finde ich ein bisschen redundant.',
            'Du weißt echt, wie man die Dinger rollen muss Bart.',
            'Das sind Drogengespräche, aber ich könnte mich auch irren. Ich muss noch mehr aus dem Kontext gerissen Sätze hören.',
            'Er hat so viel Majonäse im Körper, dass man seine Blutprobe gut an McDonalds verkaufen könnte.',
            'Hammermäßig endlich hast du mein Zimmer cool gemacht.',
            'Leute denen in die Brust geschossen wurde, sind solche Babys.',
            'Das ist soviel besser als Krankenhausbier.',
            'Ich bin nicht aus Geld gemacht, sondern aus Menschenfleisch und einem Skelett.',
            'Es wird Zeit diese blutsaugenden Geräte abzustecken, die ihre Fangzähne in unsere weißen Steckdosen schlagen, um ihren unheiligen Durst nach Elektronen zu stillen.',
            'Unfair gegenüber Erdvergiftern',
            'Lieber Gott du hast den Wind, den ich brauche. Ich habe die Gebete nachdenen du süchtig bist, machen wir einen Deal?',
            'Ich versuche hier ein sensibler Vater zu sein, du ungewollter Volltrottel.',
            'Die Natur ist eine zahnlose, sterbende Hexe.',
            'Typisch für euch Ökoärsche ihr verwendet Worte um zu reden.',
            'Oh ein Babywal meine Diät funktioniert also.',
            'Hey, ich würde alles für ein niedliches und intelligentes Säugetier tun und damit meine ich dich.',
            'Ich gebe zu mit allem, was ich bisher über Terrorismus sagte, wollte ich nur Angst vebreiten.',
            'Wieviele persönliche Freiheiten sind wir bereit noch zu opfern, nur weils im Namen der Sicherheit geschieht?',
            'Alle die dagenen sind, sagen: Ich hasse Amerika',
            'Du wolltest doch immer, dass ich die wahnsinnig teure Operation machen lasse und jetzt kann ich mir ein Motorrad leisten.',
            'Dieses Gebäude hat mir die Vorfahrt genommen.',
            'Ich muss nicht auf dich hören. Wenn mich keine Kammera filmt, siehst du mich nicht.',
            'Gott hat den Teufel erschaffen? Endlich macht er auch mal was Cooles.',
            'Ich wollte es nicht, dass so wie Big Brother wird. Ich wollte nur eine kleine Schwerster sein. Mich an alle ran kuscheln, damit die Stadt schön wird.',
            'Dieser Ralph Wiggum wird mir fehlen, er erinnert mich an meinen Sohn.',
            'Ich bin hergezogen, weil sich die Postleitzahl auf dem Taschenrechner, wie ein unanständiges Wort liesst. Eine Stadt voll er Gewinner und Skinner.',
            'Ich mag Bier, Hot Dogs und lange Blackouts am Strand.'
    ];

    scriptLoader.on('command', ['simpson', 'homer'], function (event) {
        event.channel.say('"' + _.sample(quotes) + '" — Die Simpsons');
    });
};
